global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
    - targets: ['backend:3000']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
    - targets: ['mongodb:27017']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
