

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bot-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        
        image: tardiatest/tardia-plataforma-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
        
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf 
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
  namespace: bot-platform
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
