apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  namespace: bot-platform
type: Opaque
data:
  # Creamos un dato vacío (la cadena vacía "" en base64 es "").
  # Esto es suficiente para que el pod pueda montar el volumen y arrancar.
  config: ""
