name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build and Push Images"]
    types:
      - completed
    branches:
      - main
      - develop
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Load deployment info
        id: deploy_info
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          BRANCH_NAME=$(cat branch_name.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Set up Kubeconfig Manually and Verify
        run: |
          # Creamos el directorio .kube en el home del runner, si no existe
          mkdir -p $HOME/.kube
          
          # Decodificamos el secreto (que viene de GitHub Secrets) y lo escribimos
          # directamente en el archivo de configuración que kubectl busca por defecto.
          echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
          
          echo "Kubeconfig file created. Verifying connection..."
          # Ejecutamos un comando simple para probar la conexión inmediatamente.
          # Si este comando funciona, todos los demás también lo harán.
          kubectl cluster-info

      - name: Apply Kubernetes Namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Apply RBAC Configuration
        run: kubectl apply -f k8s/rbac.yaml

      - name: Create/Update Kubernetes Secrets
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Crear bot-secrets con las API keys
          kubectl create secret generic bot-secrets \
            --from-literal=weather-api-key="$WEATHER_API_KEY" \
            --from-literal=news-api-key="$NEWS_API_KEY" \
            --from-literal=gemini-api-key="$GEMINI_API_KEY" \
            --namespace=bot-platform \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Crear app-secrets con MongoDB (con JWT ahora)
          kubectl create secret generic app-secrets \
            --from-literal=mongodb-uri="$MONGODB_URI" \
            --from-literal=jwt-secret="$JWT_SECRET" \
            --namespace=bot-platform \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          # Crear copias temporales para no modificar los originales
          cp k8s/deployment.yaml k8s/deployment-temp.yaml
          cp k8s/frontend.yaml k8s/frontend-temp.yaml
          
          # Reemplazar placeholders
          sed -i "s|YOUR_DOCKER_REGISTRY|$DOCKER_REGISTRY|g" k8s/deployment-temp.yaml
          sed -i "s|PLACEHOLDER_TAG|${{ steps.deploy_info.outputs.IMAGE_TAG }}|g" k8s/deployment-temp.yaml
          sed -i "s|YOUR_DOCKER_REGISTRY|$DOCKER_REGISTRY|g" k8s/frontend-temp.yaml
          sed -i "s|PLACEHOLDER_TAG|${{ steps.deploy_info.outputs.IMAGE_TAG }}|g" k8s/frontend-temp.yaml
          
          # Aplicar deployments
          kubectl apply -f k8s/deployment-temp.yaml
          kubectl apply -f k8s/frontend-temp.yaml

      - name: Wait for deployments
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/backend -n bot-platform
          kubectl wait --for=condition=available --timeout=180s deployment/frontend -n bot-platform

      - name: Show Deployment Status
        run: kubectl get all -n bot-platform
